const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=80',
  'https://sanand0.github.io/tdsdata/js_table/?seed=81',
  'https://sanand0.github.io/tdsdata/js_table/?seed=82',
  'https://sanand0.github.io/tdsdata/js_table/?seed=83',
  'https://sanand0.github.io/tdsdata/js_table/?seed=84',
  'https://sanand0.github.io/tdsdata/js_table/?seed=85',
  'https://sanand0.github.io/tdsdata/js_table/?seed=86',
  'https://sanand0.github.io/tdsdata/js_table/?seed=87',
  'https://sanand0.github.io/tdsdata/js_table/?seed=88',
  'https://sanand0.github.io/tdsdata/js_table/?seed=89',
];

(async () => {
  // Launch a headless (invisible) browser
  const browser = await chromium.launch();
  const page = await browser.newPage();

  let grandTotal = 0;

  for (const url of urls) {
    // Go to the page
    await page.goto(url);

    // Wait for the table to appear (it's dynamically generated by JavaScript)
    await page.waitForSelector('table');

    // Grab all text from all table cells (<td> elements)
    const cellTexts = await page.$$eval('td', cells =>
      cells.map(cell => cell.innerText.trim())
    );

    // Convert text to numbers and sum them (skip non-numeric cells)
    let pageTotal = 0;
    for (const text of cellTexts) {
      const num = parseFloat(text);
      if (!isNaN(num)) {
        pageTotal += num;
      }
    }

    console.log(`Seed URL: ${url} → Sum: ${pageTotal}`);
    grandTotal += pageTotal;
  }

  console.log(`\n✅ GRAND TOTAL across all pages: ${grandTotal}`);

  await browser.close();
})();
